Repository cse110-sp24-group17/warmup-exercise, pull requests merged in 2024-04, with the labels that each got.

#14 updated calendar to autofill dates for curr month
  index.css
  index.html
  script.js
Labels: minimum requirement, monthly display

#16 added working buttons
  index.css
  index.html
  script.js
Labels: additional feature, monthly display

#17 Calendar script
  index.css
  index.html
  polygon.svg
  script.js
Labels: additional feature, monthly display

#20 fix number of days in month
  index.css
  script.js
Labels: bug, monthly display

#21 add selectable day and highlight today
  index.css
  script.js
Labels: minimum requirement, monthly display

#24 refactor the code
  .DS_Store
  app.js
  buttons.png
  index.css
  index.html
  index.js
  modules/calendar_component.js
  modules/date_util.js
  modules/sideview_component.js
  script.js
Labels: enhancement

#30 Add gitignore
  .DS_Store
  .gitignore
Labels: enhancement

#37 add responsiveness
  index.css
Labels: enhancement
